sudo: required
language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.7.3
    - CKANVERSION=2.8.0
services:
    - redis-server
    - postgresql
addons:
    firefox: "46.0"
install:
    - bash bin/travis-build.bash
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - sh bin/travis-run.sh
after_success: coveralls
branches:
    only:
      - master
